#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/372f8025-eb69-4cc4-82f1-c698d7ec738c

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight luz_de_fondo;
  CloudLight luz_dormitorio;
  CloudLight tira_led;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/


#include "thingProperties.h"

void setup() {
  pinMode(2, OUTPUT);
  pinMode(3, OUTPUT);
  pinMode(4, OUTPUT);
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here


}


/*
  Since TiraLed is READ_WRITE variable, onTiraLedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTiraLedChange()  {
  // Add your code here to act upon TiraLed change
  if(digitalRead(2 == HIGH) {
    digitalWrite(2, LOW);
  }
  else {
    digitalWrite(2, HIGH);
  }
}


/*
  Since LuzDormitorio is READ_WRITE variable, onLuzDormitorioChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLuzDormitorioChange()  {
  // Add your code here to act upon LuzDormitorio change
    if(digitalRead(3 == HIGH) {
    digitalWrite(3, LOW);
  }
  else {
    digitalWrite(3, HIGH);
  }
}

/*
  Since LuzDeFondo is READ_WRITE variable, onLuzDeFondoChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLuzDeFondoChange()  {
  // Add your code here to act upon LuzDeFondo change
    if(digitalRead(4 == HIGH) {
    digitalWrite(4, LOW);
  }
  else {
    digitalWrite(4, HIGH);
  }
}
