// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "01c2539c-6c1d-47de-944b-4f99528a4657";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLuzDeFondoChange();
void onLuzDormitorioChange();
void onTiraLedChange();

CloudLight luz_de_fondo;
CloudLight luz_dormitorio;
CloudLight tira_led;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(luz_de_fondo, READWRITE, ON_CHANGE, onLuzDeFondoChange);
  ArduinoCloud.addProperty(luz_dormitorio, READWRITE, ON_CHANGE, onLuzDormitorioChange);
  ArduinoCloud.addProperty(tira_led, READWRITE, ON_CHANGE, onTiraLedChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
